export const contactItems = [
	{
		href: "tel:030111222333",
		label: "Telefon",
		hrefText: "030111222333"
	},
	{
		href: "mailto:info@ee-gr.de",
		label: "E-Mail",
		hrefText: "info@ee-gr.de"
	},
	{
		href: "https://ee-gr.de",
		label: "Webseite",
		hrefText: "ee-gr.de"
	}
];

export const companyInfos = ["E&E-Gebäudereiniguing", "Sandstraße 64", "13593 Berlin"];

export const ImpressumItems = [
	{
		label: "Handwerkskammer:",
		text: "Handwerkskammer Berlin"
	},
	{
		label: "Berufshaftpflichtversicherung:",
		text: "andsafe Aktiengesellschaft Provinzial-Allee 148159 Münster"
	},
	{
		label: "Steuernummer:",
		text: "68/409/615/326"
	}
];
